### PR TITLE
DET-6 Retired state for contacts

### PR DESCRIPTION
**Pull request by ericanand**

### CODE REVIEW

**Comment by GeoffThorpeFT** [comment]
Well done, looks good. Nice default of 'Active'.
We will look at the index page and filtering in a subsequent release.

**Comment by GeoffThorpeFT** [comment]
However, did you mean to commit this branch to master or test. we normally push to test first and then push from test to master

**Comment by ericanand** [comment]
Ah apologies @GeoffThorpeFT, should have probably guessed that - just used to normally merging to master. I guess I'm going to have to make a new pull request?

**Comment by ericanand** [comment]
Scratch that - changed the base to Test @GeoffThorpeFT

**Comment by GeoffThorpeFT** [comment]
great, thanks!

**Comment by ericanand** [comment]
@GeoffThorpeFT @AlanTurner Could someone please approve this so I can release to test please?

**Comment by GeoffThorpeFT** [comment]
approved!

**Pull request merged**
